### ISSUE TITLE
Noob question about how to static link libduckdb using zuckdb 

### ISSUE THREAD

**Issue by zigster64** [karlseguin/zuckdb.zig#2]
I haven't really done any work with Zig + external C libs yet, so please excuse the noob question about linking.

This is all on Mac / M1 / Sonoma, with zig 0.11.  It may be a Mac issue, don't know.

No problems building a Zig app and dynamically linking with libduckdb via zuckdb. That all works great.

What I want to do is build an app that uses zuckdb, and statically link the installed libduckdb_static.a into my app, instead of libduckdb.dylib

On Mac, brew install gives /opt/homebrew/libs/libduckdb_static.a
Pulling in duckdb src from git, and building locally also provides build/releases/src/libduckdb_static.a
Running `ar` on this archive confirms that its a collection of object code ... so far so good

What I have tried : 

In my build.zig, I am dynamically linking using this ...

```
    const lib_path = LazyPath.relative("lib");
    exe.addRPath(lib_path);
    exe.addLibraryPath(lib_path);
    exe.addIncludePath(lib_path);
    exe.linkSystemLibrary("duckdb");
```
That builds fine, runs fine, everything works.

To attempt to force static linking, In my build.zig, I change it to this ....

```
    const lib_path = LazyPath.relative("lib");
    exe.addRPath(lib_path);
    exe.addLibraryPath(lib_path);
    exe.addIncludePath(lib_path);
    exe.linkSystemLibrary2("duckdb_static", .{ .preferred_link_mode = .Static });
```

That gives a compile error of "error: NotObject"

Not sure whats next (or maybe it's an LLVM + Mac issue even).  Any ideas ?

**Comment by karlseguin** [comment]
I also wasn't able to get this working. I took out this library from the equation:

```
const std = @import("std");
const c = @cImport(@cInclude("duckdb.h"));

pub fn main() !void {
    var gpa = std.heap.GeneralPurposeAllocator(.{}){};
    const allocator = gpa.allocator();

    var config_slice = try allocator.alignedAlloc(u8, 8, 8);
    const config: *c.duckdb_config = @ptrCast(config_slice.ptr);
    std.debug.print("{any}\n", .{c.duckdb_create_config(config)});
}
```

And with: 
```
zig build-exe test.zig --name test  -I lib -L lib -lc -lduckdb_static
```

Which is like using this build.zig:

```zig
step.addLibraryPath(LazyPath.relative("lib"));
step.addIncludePath(LazyPath.relative("lib"));
step.linkSystemLibrary("duckdb_static");
```

I get a bunch of `undefined reference to symbol` errors. Even though those symbols are in `lib/libduckdb_static.a`

**Comment by zigster64** [comment]
Interesting… good to hear though. I see the Go devs had similar issues, but eventually solved it I think.

My motivation for wanting static linking is for shipping a “finished product” to consumers in a single file … but that is still a long way in the future for me yet.

I will persist with DuckDB for my next project then, in the hope that we can fix the linking issue later on. Shouldn’t be too impossible to do you would think. Is not a high priority problem yet.

The API wrapper is nice and light, be interesting to see how it goes using it in a project, compared to Postgres + sqlx in Go.

My project im converting (from Go) has a Postgres DB with around 40 regular tables over 5 schemas, plus half a dozen timeseries tables. The primary data is in a tree struct. Everything keyed on UUIDs. Should be fun :)

**Comment by karlseguin** [comment]
I _might_ have this working, thanks to this commit: https://github.com/duckdb/duckdb/pull/10507

Build duckdb using the new `bundle-library` target. (Make sure you're on the `v0.10.0` tag). This will give you a `build/release/libduckdb_bundle.a`. Copy it to `$(your_zig_project)/lib/libduckdb.a`. Also copy `src/include/duckdb.h` to $(your_zig_project)/lib/duckdb.h`

In your build, add:
```
exe.linkSystemLibrary("duckdb");
exe.linkSystemLibrary("stdc++");
exe.addLibraryPath(LazyPath.relative("lib/"));
```

And..that worked for me.

/cc @zigster64

**Comment by zigster64** [comment]
Nice work !

I believe that should fix it. There is a msg on discord/projects/DuckDB extensions 
That suggests building DuckDB libs from src using zig as the c++ compiler too

I think we can close this now, ta
