### ISSUE TITLE
Appender API support

### ISSUE THREAD

**Issue by recursiveGecko** [karlseguin/zuckdb.zig#3]
Hi, are there any plans to support DuckDB's Appender API? From my limited testing, it unlocks an astronomical amount of performance when appending data in tight loops.

After an exchange with a DuckDB developer who pointed me towards the Appender API, I observed the following performance characteristics of my program which inserts ~10k rows (~40 bytes each) on a small sample dataset. Sample size of 1:

> Baseline runtime without DuckDB: ~5-6s
> Prepared INSERT statements with automatic transactions: ~27s
> Prepared INSERT statements with manual transaction wrapping all INSERT operations: ~10s
> Appender API: ~6s

I'd be happy to contribute to implementation with some guidance.

General documentation: https://duckdb.org/docs/data/appender

API documentation: https://duckdb.org/docs/api/c/appender.html

**Comment by karlseguin** [comment]
I've been avoiding it because it can't deal with default values.

I didn't get to play with it much, so I'm not going to officially document it, but if you have a chance to play with the latest, please let me know how it works out:

```zig
var appender = try conn.appender("schema_or_null", "table");
defer appender.deinit();

try appender.append("over");
try appender.append(9000);
try appender.endRow()

// append another row
```

You can use `appender.err() ?[]const u8` which will return the duckdb error message (if there is any). This is automatically freed with `appender.deinit` is called.

**Comment by recursiveGecko** [comment]
That was quick, thank you! I'm trying it out now, found a small bug #5 but otherwise it appears to be working fine.

**Comment by karlseguin** [comment]
Heads up that this implementation is being changed, and the API is going to change slightly. There's an [appender branch](https://github.com/karlseguin/zuckdb.zig/tree/appender) where the work is taking place. The main goal is to add support for appending single-dimension lists, which wasn't possible using the original API (the DuckDB C api doesn't support it). However by writing to the underlying data_chunk and vectors directly (as the Go driver does), we can do anything we want.
