### ISSUE TITLE
Next/first release tag

### ISSUE THREAD

**Issue by softprops** [karlseguin/zuckdb.zig#6]
This lib looks fantastic. Any plans for cutting a first release tag? I noticed there wasn’t one yet but this looks fairly usable already in its current state. I don’t see a tag I could use  https://github.com/karlseguin/zuckdb.zig/tags

**Comment by karlseguin** [comment]
Is there really any value in that? Zig's build lets you reference a commit

**Comment by softprops** [comment]
They communicate progress but also [semantics](https://semver.org/) of what check points are intended for callers to depend on and how dependents can reason about rolling updates.

**Comment by karlseguin** [comment]
Maybe once Zig stabilizes, but right now everything too much of a moving target to maintain that.
